In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\hp\Downloads\ecom data\e_commerce_sales_data.csv")
df.head(5)

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,North,NaN,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18
4,CUST0173,Female,South,NaN,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19

In [4]:
df.shape

(1000, 12)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      1000 non-null   str
 1   Gender           1000 non-null   str
 2   Region           950 non-null    str
 3   Age              900 non-null    float64
 4   Product Name     1000 non-null   str
 5   Category         1000 non-null   str
 6   Unit Price       1000 non-null   float64
 7   Quantity         1000 non-null   int64
 8   Total Price      1000 non-null   int64
 9   Shipping Fee     1000 non-null   float64
 10  Shipping Status  950 non-null    str
 11  Order Date       1000 non-null   str
dtypes: float64(3), int64(2), str(7)
memory usage: 93.9 KB

In [6]:
df.describe()

              Age   Unit Price     Quantity  Total Price  Shipping Fee
count  900.000000  1000.000000  1000.000000  1000.000000   1000.000000
mean    46.695556   457.703777     3.008000  1346.600000     12.416390
std     15.011400   537.231434     1.404246  1834.037877      4.412185
min     18.000000    30.000000     1.000000    30.000000      5.000000
25%     35.000000    50.000000     2.000000   200.000000      8.560000
50%     49.000000   200.000000     3.000000   600.000000     12.315000
75%     59.000000   800.000000     4.000000  1500.000000     16.075000
max     69.000000  3109.560612     5.000000  7500.000000     19.980000

In [7]:
df.isnull().sum()

Customer ID          0
Gender               0
Region              50
Age                100
Product Name         0
Category             0
Unit Price           0
Quantity             0
Total Price          0
Shipping Fee         0
Shipping Status     50
Order Date           0
dtype: int64

In [8]:
df['Age'] = df['Age'].fillna(df['Age'].median())
df.head(5)

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,North,49.0,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18
4,CUST0173,Female,South,49.0,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19

In [9]:
df.head(5)

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,North,49.0,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18
4,CUST0173,Female,South,49.0,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19

In [10]:
df.isnull().sum()

Customer ID         0
Gender              0
Region             50
Age                 0
Product Name        0
Category            0
Unit Price          0
Quantity            0
Total Price         0
Shipping Fee        0
Shipping Status    50
Order Date          0
dtype: int64

In [11]:
df['Region'] = df['Region'].fillna('Unknown')
df['Shipping Status'] = df['Shipping Status'].fillna('Unknown')

In [12]:
df.isnull().sum()

Customer ID        0
Gender             0
Region             0
Age                0
Product Name       0
Category           0
Unit Price         0
Quantity           0
Total Price        0
Shipping Fee       0
Shipping Status    0
Order Date         0
dtype: int64

In [13]:
df.head(5)

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date
0,CUST0268,Male,North,49.0,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18
4,CUST0173,Female,South,49.0,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Customer ID      1000 non-null   str
 1   Gender           1000 non-null   str
 2   Region           1000 non-null   str
 3   Age              1000 non-null   float64
 4   Product Name     1000 non-null   str
 5   Category         1000 non-null   str
 6   Unit Price       1000 non-null   float64
 7   Quantity         1000 non-null   int64
 8   Total Price      1000 non-null   int64
 9   Shipping Fee     1000 non-null   float64
 10  Shipping Status  1000 non-null   str
 11  Order Date       1000 non-null   str
dtypes: float64(3), int64(2), str(7)
memory usage: 93.9 KB

In [15]:
df['Customer ID'].nunique()

292

In [16]:
# Recalculate corrected Unit Price where mismatch exists
mask = (df['Unit Price'] * df['Quantity'] - df['Total Price']).abs() > 0.01
df.loc[mask, 'Unit Price'] = df.loc[mask, 'Total Price'] / df.loc[mask, 'Quantity']

In [17]:
# RFM Analysis
df['Order Date'] = pd.to_datetime(df['Order Date'])
snapshot_date = df['Order Date'].max() + pd.Timedelta(days=1)

rfm = df.groupby('Customer ID').agg(
    Recency=('Order Date', lambda x: (snapshot_date - x.max()).days),
    Frequency=('Customer ID', 'count'),
    Monetary=('Total Price', 'sum')
).reset_index()

# Score 1-5 for each (5 = best)
rfm['R_Score'] = pd.qcut(rfm['Recency'], 5, labels=[5,4,3,2,1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 5, labels=[1,2,3,4,5])
rfm['M_Score'] = pd.qcut(rfm['Monetary'], 5, labels=[1,2,3,4,5])

rfm['RFM_Score'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)

def segment(row):
    r, f, m = row['R_Score'], row['F_Score'], row['M_Score']
    
    if r >= 4 and f >= 4 and m >= 4:
        return 'Champions'
    elif r >= 3 and f >= 3:
        return 'Loyal Customers'
    elif r >= 4 and f <= 2:
        return 'New/Promising'
    elif r <= 2 and f >= 4:
        return 'At Risk'
    elif r <= 2 and f <= 2 and m <= 2:
        return 'Lost'
    elif r >= 3 and m >= 4:
        return 'Big Spenders'
    else:
        return 'Needs Attention'

rfm['Segment'] = rfm.apply(segment, axis=1)


df = df.merge(rfm[['Customer ID', 'Recency', 'Frequency', 'Monetary', 'RFM_Score','Segment']], 
              on='Customer ID', how='left')
df.head()

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date,Recency,Frequency,Monetary,RFM_Score,Segment
0,CUST0268,Male,North,49.0,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08,27,5,3540,453,Loyal Customers
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09,19,5,7760,545,Champions
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28,129,1,300,211,Lost
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18,116,3,1550,222,Lost
4,CUST0173,Female,South,49.0,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19,13,4,9250,545,Champions

In [21]:
df['Order Month'] = df['Order Date'].dt.to_period('M').astype(str)
df['Order Year'] = df['Order Date'].dt.year

In [22]:
df.head(5)

,Customer ID,Gender,Region,Age,Product Name,Category,Unit Price,Quantity,Total Price,Shipping Fee,Shipping Status,Order Date,Recency,Frequency,Monetary,RFM_Score,Segment,Order Month,Order Year
0,CUST0268,Male,North,49.0,Monitor,Electronics,300.0,5,1500,13.31,Returned,2023-12-08,27,5,3540,453,Loyal Customers,2023-12,2023
1,CUST0046,Male,West,22.0,Headphones,Accessories,100.0,2,200,6.93,In Transit,2023-04-09,19,5,7760,545,Champions,2023-04,2023
2,CUST0169,Female,South,54.0,Monitor,Electronics,300.0,1,300,11.31,Returned,2023-08-28,129,1,300,211,Lost,2023-08,2023
3,CUST0002,Male,North,23.0,Headphones,Accessories,100.0,5,500,12.22,Delivered,2023-01-18,116,3,1550,222,Lost,2023-01,2023
4,CUST0173,Female,South,49.0,Laptop,Electronics,1500.0,3,4500,5.40,Delivered,2023-01-19,13,4,9250,545,Champions,2023-01,2023

In [23]:
df.to_csv(r"C:\Users\hp\Downloads\ecom data\clean_data.csv")